### PR TITLE
forge 1.20-1.21.3 support

### PR DESCRIPTION
**Pull request by Lemonnik6484**
do bubir accep 🦫

### CODE REVIEW

**Comment by Lemonnik6484** [comment]
frog? 
изображение_2024-11-26_225145477

**Comment by JXSnack** [comment]
Awesome! Before I can merge, please remove the comments from the main file which are redundant (so it's similar to fabric) and also all the block registration example stuff -- that's it!

**Comment by Lemonnik6484** [comment]
bubir done
image

**Comment by JXSnack** [comment]
bunurbu acupt :D

**Pull request merged**
